### ISSUE TITLE
Error in aarch64 using docker-compose

### ISSUE THREAD

**Issue by akang943578** [Amery2010/TalkWithGemini#1]
My server is based on Oracle aarch64 4c24g, there is error after deployed:

docker-compose.yml:
```
services:
  talk-with-gemini:
    container_name: talk-with-gemini
    image: xiangfa/talk-with-gemini
    ports:
      - "3208:3000"
    restart: always
    environment:
      - GEMINI_API_KEY=AIzaSyAo5.....
      - ACCESS_PASSWORD=*****
```

Error message: 

Application error: a client-side exception has occurred (see the browser console for more information).
<img width="1467" alt="image" src="https://github.com/Amery2010/TalkWithGemini/assets/17521632/13712492-3c19-4395-a2ff-cc8005498b93">

Error in browser console:
TypeError: undefined is not a constructor
